name: stake_fair_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.4+3

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.18.1
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  country_picker: ^2.0.27
  intl_phone_field: ^3.2.0
  firebase_core: ^3.12.0
  firebase_database: ^11.3.3         # Upgraded version for compatibility with firebase_core ^3.12.0
  package_info_plus: ^8.2.1
  flutter_downloader: ^1.10.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.2
  open_file: ^3.3.2
  dio: ^5.4.0 
  http: ^1.3.0
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.3.9
  badges: ^3.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
