// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxHj_QkDZJhJ3Dd3OAk0ZzhUTFvxXz5Dg',
    appId: '1:286932819261:web:21b5b5e3a02723b928f954',
    messagingSenderId: '286932819261',
    projectId: 'stakefair-d9fa9',
    authDomain: 'stakefair-d9fa9.firebaseapp.com',
    storageBucket: 'stakefair-d9fa9.firebasestorage.app',
    measurementId: 'G-Z0L9W4W02N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLkm5LV2cA7YrRqb4GFArwsmW9GoZjEeY',
    appId: '1:286932819261:android:2e962ddd7e45e04a28f954',
    messagingSenderId: '286932819261',
    projectId: 'stakefair-d9fa9',
    storageBucket: 'stakefair-d9fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcpZC5n_4TyZb6eXIBWZTOazBRWbF0csA',
    appId: '1:286932819261:ios:de1a6b6b70cc60e828f954',
    messagingSenderId: '286932819261',
    projectId: 'stakefair-d9fa9',
    storageBucket: 'stakefair-d9fa9.firebasestorage.app',
    iosBundleId: 'com.example.stakeFairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcpZC5n_4TyZb6eXIBWZTOazBRWbF0csA',
    appId: '1:286932819261:ios:de1a6b6b70cc60e828f954',
    messagingSenderId: '286932819261',
    projectId: 'stakefair-d9fa9',
    storageBucket: 'stakefair-d9fa9.firebasestorage.app',
    iosBundleId: 'com.example.stakeFairApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxHj_QkDZJhJ3Dd3OAk0ZzhUTFvxXz5Dg',
    appId: '1:286932819261:web:999137d0ea56af0928f954',
    messagingSenderId: '286932819261',
    projectId: 'stakefair-d9fa9',
    authDomain: 'stakefair-d9fa9.firebaseapp.com',
    storageBucket: 'stakefair-d9fa9.firebasestorage.app',
    measurementId: 'G-1W9TCQJYBX',
  );
}
